services:
  postgres:
    image: postgres:18.1
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-book-store}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
